# Dependencies
highlighter: rouge
markdown: kramdown

# Setup
title:            Muammer Beslen 
tagline:          'A Personal Page'
description:      'Personal blog about my cv'
url:              
baseurl:          /

# Custom vars
socials_links:
- url: https://github.com/drmuammer
  class: fab fa-github
- url: https://www.kaggle.com/muammerbeslen
  class: fab icon-duckduckgo
- url: https://www.instagram.com/kirikdr
  class: fab fa-instagram
- url: https://www.codewars.com/users/Drmuammer
  class: fab icon-pitch
- url: https://wa.me/5412819889?
  class: fab icon-whatsapp
# paginate: 5
# paginate_path: 'blog.html'

github:
  repo:           https://github.com/drmuammer

plugins: [kramdown, rouge]

kramdown:
  input: GFM
  syntax_highlighter: rouge


collections:
  works: 
    output: true 

#custom icons
favicon: /favicon.ico
apple_touch_icon: /assets/img/logo.png

